"""create user_table

Revision ID: 0431ea29ef5e
Revises: 9fd0f5563195
Create Date: 2025-11-02 00:50:30.899133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0431ea29ef5e'
down_revision: Union[str, Sequence[str], None] = '9fd0f5563195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_number', sa.BigInteger(), nullable=True),
    sa.Column('user_door_no', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('user_city', sa.String(), nullable=True),
    sa.Column('user_pincode', sa.String(), nullable=True),
    sa.Column('Landmark', sa.String(), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_info_user_email'), 'user_info', ['user_email'], unique=False)
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=False)
    op.drop_index(op.f('ix_User_Info_user_email'), table_name='User_Info')
    op.drop_index(op.f('ix_User_Info_user_id'), table_name='User_Info')
    op.drop_table('User_Info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Info',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_door_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Landmark', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('User_Info_pkey'))
    )
    op.create_index(op.f('ix_User_Info_user_id'), 'User_Info', ['user_id'], unique=False)
    op.create_index(op.f('ix_User_Info_user_email'), 'User_Info', ['user_email'], unique=False)
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_user_email'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
