"""create user_table

Revision ID: 0fab30bf9f89
Revises: 
Create Date: 2025-11-01 19:40:06.956434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fab30bf9f89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Info',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_number', sa.BigInteger(), nullable=True),
    sa.Column('user_door_no', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('user_city', sa.String(), nullable=True),
    sa.Column('user_pincode', sa.String(), nullable=True),
    sa.Column('Landmark', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_Info_user_id'), 'User_Info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Info_user_id'), table_name='User_Info')
    op.drop_table('User_Info')
    # ### end Alembic commands ###
