"""create user_table

Revision ID: 202e4703eba3
Revises: f8597a9de302
Create Date: 2025-11-02 23:54:21.853701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202e4703eba3'
down_revision: Union[str, Sequence[str], None] = 'f8597a9de302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_info',
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pro_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['product_info.pro_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_cart_info_cart_id'), 'cart_info', ['cart_id'], unique=False)
    op.create_table('past_order_info',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pro_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('delivery_type', sa.String(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['product_info.pro_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_past_order_info_order_id'), 'past_order_info', ['order_id'], unique=False)
    op.create_table('order_tracking_status',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['past_order_info.order_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_order_tracking_status_track_id'), 'order_tracking_status', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_tracking_status_track_id'), table_name='order_tracking_status')
    op.drop_table('order_tracking_status')
    op.drop_index(op.f('ix_past_order_info_order_id'), table_name='past_order_info')
    op.drop_table('past_order_info')
    op.drop_index(op.f('ix_cart_info_cart_id'), table_name='cart_info')
    op.drop_table('cart_info')
    # ### end Alembic commands ###
