"""create user_table

Revision ID: 7077e313bb3d
Revises: 9acf00110866
Create Date: 2025-11-02 07:50:56.602082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7077e313bb3d'
down_revision: Union[str, Sequence[str], None] = '9acf00110866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product_info', 'catgories_info', ['cat_id'], ['cat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_info', type_='foreignkey')
    # ### end Alembic commands ###
