"""create user_table

Revision ID: 737e2052a57b
Revises: 202e4703eba3
Create Date: 2025-11-04 20:20:56.062108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737e2052a57b'
down_revision: Union[str, Sequence[str], None] = '202e4703eba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Instead of nullable=False, add a default
    op.add_column(
        'past_order_info',
        sa.Column('status', sa.String(), nullable=False, server_default='PENDING')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_order_info', 'status')
    op.create_table('order_tracking_status',
    sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['past_order_info.order_id'], name=op.f('order_tracking_status_order_id_fkey')),
    sa.PrimaryKeyConstraint('track_id', name=op.f('order_tracking_status_pkey'))
    )
    op.create_index(op.f('ix_order_tracking_status_track_id'), 'order_tracking_status', ['track_id'], unique=False)
    # ### end Alembic commands ###
