"""create user_table

Revision ID: 975a6f45d7d3
Revises: 0431ea29ef5e
Create Date: 2025-11-02 00:54:01.902472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975a6f45d7d3'
down_revision: Union[str, Sequence[str], None] = '0431ea29ef5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catgories_info',
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('cat_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_index(op.f('ix_catgories_info_cat_id'), 'catgories_info', ['cat_id'], unique=False)
    op.create_table('product_info',
    sa.Column('pro_id', sa.String(), nullable=False),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pro_id')
    )
    op.create_index(op.f('ix_product_info_cat_id'), 'product_info', ['cat_id'], unique=False)
    op.create_index(op.f('ix_product_info_pro_id'), 'product_info', ['pro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_pro_id'), table_name='product_info')
    op.drop_index(op.f('ix_product_info_cat_id'), table_name='product_info')
    op.drop_table('product_info')
    op.drop_index(op.f('ix_catgories_info_cat_id'), table_name='catgories_info')
    op.drop_table('catgories_info')
    # ### end Alembic commands ###
