"""create user_table

Revision ID: 9acf00110866
Revises: 975a6f45d7d3
Create Date: 2025-11-02 07:46:42.653778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acf00110866'
down_revision: Union[str, Sequence[str], None] = '975a6f45d7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catgories_info', sa.Column('cat_img', sa.String(), nullable=False))
    op.add_column('product_info', sa.Column('product_Img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'product_Img')
    op.drop_column('catgories_info', 'cat_img')
    # ### end Alembic commands ###
