"""create user_table

Revision ID: 9aeb7fa2be55
Revises: 7077e313bb3d
Create Date: 2025-11-02 08:00:24.683632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aeb7fa2be55'
down_revision: Union[str, Sequence[str], None] = '7077e313bb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'catgories_info', ['cat_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catgories_info', type_='unique')
    # ### end Alembic commands ###
