"""create user_table

Revision ID: 9fd0f5563195
Revises: 0fab30bf9f89
Create Date: 2025-11-02 00:32:30.763972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd0f5563195'
down_revision: Union[str, Sequence[str], None] = '0fab30bf9f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Info', sa.Column('created_by', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_User_Info_user_email'), 'User_Info', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Info_user_email'), table_name='User_Info')
    op.drop_column('User_Info', 'created_by')
    # ### end Alembic commands ###
